version: '3.8'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'fxplorer'
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'password'
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres